// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfeExplorer_Api.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NfeExplorer_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NfeExplorer_Api.Models.Destinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomePessoa")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Emitente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Emitentes");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.ImpostosNfe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AliquotaIcms")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseCalculoICMS")
                        .HasColumnType("numeric");

                    b.Property<Guid>("IdNotaFiscal")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorCOFINS")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorICMS")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorNota")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPIS")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorProdutos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotalTributos")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdNotaFiscal")
                        .IsUnique();

                    b.ToTable("ImpostosNfes");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdDestinatario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEmitente")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTransportadora")
                        .HasColumnType("uuid");

                    b.Property<string>("NaturezaOperacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoNota")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdDestinatario");

                    b.HasIndex("IdEmitente");

                    b.HasIndex("IdTransportadora");

                    b.ToTable("NotaFiscais");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdNotaFiscal")
                        .HasColumnType("uuid");

                    b.Property<string>("NCM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdNotaFiscal");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Transportadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<int>("ModalidadeFrete")
                        .HasColumnType("integer");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transportadoras");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.ImpostosNfe", b =>
                {
                    b.HasOne("NfeExplorer_Api.Models.NotaFiscal", "NotaFiscal")
                        .WithOne("ImpostosNfe")
                        .HasForeignKey("NfeExplorer_Api.Models.ImpostosNfe", "IdNotaFiscal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.NotaFiscal", b =>
                {
                    b.HasOne("NfeExplorer_Api.Models.Destinatario", "Destinatario")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("IdDestinatario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NfeExplorer_Api.Models.Emitente", "Emitente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("IdEmitente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NfeExplorer_Api.Models.Transportadora", "Transportadora")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("IdTransportadora");

                    b.Navigation("Destinatario");

                    b.Navigation("Emitente");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Produto", b =>
                {
                    b.HasOne("NfeExplorer_Api.Models.NotaFiscal", "NotaFiscal")
                        .WithMany("Produtos")
                        .HasForeignKey("IdNotaFiscal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Destinatario", b =>
                {
                    b.Navigation("NotasFiscais");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Emitente", b =>
                {
                    b.Navigation("NotasFiscais");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.NotaFiscal", b =>
                {
                    b.Navigation("ImpostosNfe");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("NfeExplorer_Api.Models.Transportadora", b =>
                {
                    b.Navigation("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
